# Database Credentials
#db.driverName = com.mysql.cj.jdbc.Driver
#db.connectionString = jdbc:mysql://localhost:2025/MYSHOP
#db.username = root
#db.password = admin

# Database Credentials
db.driverName = com.microsoft.sqlserver.jdbc.SQLServerDriver
db.connectionString = jdbc:sqlserver://localhost:1433;databaseName=MYSHOP;encrypt=true;trustServerCertificate=true
#db.connectionURL = jdbc:sqlserver://MANISHKUMAR:1433;databaseName=MYSHOP;user=Admin;password=Admin@123
db.username = sa
db.password = Admin@123

#Mailer Credentials
mailer.email=themyshop2025@gmail.com
mailer.password=fhga bwxm hpkd waia

#Data Source=MANISHKUMAR;Initial Catalog=MYSHOP;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Application Name="SQL Server Management Studio";Command Timeout=0