SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- SCHEMA
CREATE SCHEMA IF NOT EXISTS `MYSHOP` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `MYSHOP`;

-- PRODUCTS table (unchanged)
DROP TABLE IF EXISTS `MYSHOP`.`PRODUCTS`;
CREATE TABLE IF NOT EXISTS `MYSHOP`.`PRODUCTS`(
    `pId` VARCHAR(45) NOT NULL,
    `pName` VARCHAR(100) DEFAULT NULL,
    `pType` VARCHAR(20) DEFAULT NULL,
    `pInfo` VARCHAR(350) DEFAULT NULL,
    `pPrice` DECIMAL(12,2) DEFAULT NULL,
    `pQuantity` INT DEFAULT NULL,
    `image` LONGBLOB DEFAULT NULL,
    PRIMARY KEY (`pId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ORDERS table (modified)
DROP TABLE IF EXISTS `MYSHOP`.`ORDERS`;
CREATE TABLE IF NOT EXISTS `MYSHOP`.`ORDERS`(
    `orderId` VARCHAR(45) NOT NULL,
    `prodId` VARCHAR(250) NOT NULL,
    `quantity` INT DEFAULT NULL,
    `amount` DECIMAL(10,2) DEFAULT NULL,
    `order_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `delivery_date` DATE DEFAULT NULL,
    `shipped` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`orderId`, `prodId`),
    INDEX `productId_idx` (`prodId` ASC),
    CONSTRAINT `productId` FOREIGN KEY (`prodId`) REFERENCES `MYSHOP`.`PRODUCTS`(`pId`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Trigger to auto-set delivery_date 7 days after order_date
DELIMITER //
CREATE TRIGGER set_delivery_date
BEFORE INSERT ON `ORDERS`
FOR EACH ROW
BEGIN
    IF NEW.delivery_date IS NULL THEN
        SET NEW.delivery_date = DATE_ADD(NEW.order_date, INTERVAL 7 DAY);
    END IF;
END;
//
DELIMITER ;

-- USER table (unchanged)
DROP TABLE IF EXISTS `MYSHOP`.`USER`;
CREATE TABLE IF NOT EXISTS `MYSHOP`.`USER`(
    `image` LONGBLOB DEFAULT NULL,
    `email` VARCHAR(60) NOT NULL,
    `name` VARCHAR(30) DEFAULT NULL,
    `mobile` VARCHAR(12) DEFAULT NULL,
    `address` VARCHAR(500) DEFAULT NULL,
    `pincode` INT DEFAULT NULL,
    `password` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- TRANSACTIONS table (unchanged)
DROP TABLE IF EXISTS `MYSHOP`.`TRANSACTIONS`;
CREATE TABLE IF NOT EXISTS `MYSHOP`.`TRANSACTIONS`(
    `transId` VARCHAR(45) NOT NULL,
    `userName` VARCHAR(60) DEFAULT NULL,
    `time` DATETIME DEFAULT NULL,
    `amount` DECIMAL(10,2) DEFAULT NULL,
    PRIMARY KEY (`transId`),
    INDEX `trUserId_idx` (`userName` ASC),
    CONSTRAINT `trUserId` FOREIGN KEY (`userName`) REFERENCES `MYSHOP`.`USER`(`email`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `transOrderId` FOREIGN KEY (`transId`) REFERENCES `MYSHOP`.`ORDERS`(`orderId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- USER_DEMAND table (unchanged)
DROP TABLE IF EXISTS `MYSHOP`.`USER_DEMAND`;
CREATE TABLE IF NOT EXISTS `MYSHOP`.`USER_DEMAND`(
    `userName` VARCHAR(60) NOT NULL,
    `prodId` VARCHAR(45) NOT NULL,
    `quantity` INT DEFAULT NULL,
    PRIMARY KEY (`userName`, `prodId`),
    INDEX `prodId_idx` (`prodId` ASC),
    CONSTRAINT `userdEmailEmail` FOREIGN KEY (`userName`) REFERENCES `MYSHOP`.`USER`(`email`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `prodId` FOREIGN KEY (`prodId`) REFERENCES `MYSHOP`.`PRODUCTS`(`pId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- USERCART table (unchanged)
DROP TABLE IF EXISTS `MYSHOP`.`USERCART`;
CREATE TABLE IF NOT EXISTS `MYSHOP`.`USERCART`(
    `username` VARCHAR(60) DEFAULT NULL,
    `prodid` VARCHAR(45) DEFAULT NULL,
    `quantity` INT DEFAULT NULL,
    INDEX `useremail_idx` (`username` ASC),
    INDEX `prodidcart_idx` (`prodid` ASC),
    CONSTRAINT `useremail` FOREIGN KEY (`username`) REFERENCES `MYSHOP`.`USER`(`email`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `prodIdcart` FOREIGN KEY (`prodid`) REFERENCES `MYSHOP`.`PRODUCTS`(`pId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- DELIVERYSTAFF table (unchanged)
DROP TABLE IF EXISTS `MYSHOP`.`DELIVERYSTAFF`;
CREATE TABLE IF NOT EXISTS `MYSHOP`.`DELIVERYSTAFF`(
    `simage` LONGBLOB DEFAULT NULL,
    `semail` VARCHAR(60) NOT NULL,
    `sname` VARCHAR(30) DEFAULT NULL,
    `smobile` VARCHAR(12) DEFAULT NULL,
    `spassword` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`semail`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `MYSHOP`.`ASSIGNORDERFORSTAFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MYSHOP`.`ASSIGNORDERFORSTAFF` ;

CREATE TABLE ASSIGNORDERFORSTAFF (
    assignId INT AUTO_INCREMENT PRIMARY KEY,
    prodId VARCHAR(45) NULL,
    orderId VARCHAR(45) NOT NULL,        
    staffId VARCHAR(20) NOT NULL,
    staffName VARCHAR(30) NULL,
    assignedDate DATE,
    deliveryStatus VARCHAR(20),
    otp VARCHAR(10),
    otpGeneratedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remarks VARCHAR(255),
    CONSTRAINT fk_orderId FOREIGN KEY(orderId) REFERENCES orders(orderId)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT fk_prodId FOREIGN KEY(prodId) REFERENCES products(pId)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_staffId FOREIGN KEY (staffId) REFERENCES deliverystaff(semail)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) 
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE admin (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    admin_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    mobile VARCHAR(15),
    role VARCHAR(20) DEFAULT 'ADMIN',
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

-- Restore original settings
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- -----========================---------
use myshop;
ALTER TABLE `MYSHOP`.`USER`
ADD COLUMN `email_verified` TINYINT(1) NOT NULL DEFAULT 1,   -- email verified by default
ADD COLUMN `mobile_verified` TINYINT(1) NOT NULL DEFAULT 0;  -- mobile not verified by default

SELECT * FROM ORDERS;
SELECT * FROM USER;
desc DELIVERYstaff;
SELECT * FROM PRODUCTS;
SELECT * FROM TRANSACTIONS;
SELECT * FROM USER_DEMAND;
SELECT * FROM USERCART;
SELECT * FROM ASSIGNORDERFORSTAFF;
SELECT * FROM DELIVERYSTAFF;
select * from admin;

update ASSIGNORDERFORSTAFF set otp= "879086", deliveryStatus="OUT_FOR_DELIVERY" where assignid=1002 And orderid = "T20260109020328";


SELECT o.orderId, o.status, o.delivery_date, 
            u.name, u.email, a.staffId, a.otp 
            FROM orders o 
            JOIN user u ON o.orderId = u.orderId
		    JOIN assignorderforstaff a ON o.orderId = a.orderId 
            WHERE o.status IN ('OUT_FOR_DELIVERY', 'DELIVERED');
            
            


INSERT INTO admin (admin_name, email, password, mobile)
VALUES (
    'Super Admin',
    'admin123@gmail.com',
    'YWRtaW4=',
    '6206848898'
);

